### ISSUE TITLE
TKAdjustableNumber works strangely without data-min and -max variables

### ISSUE THREAD

**Issue by ghost** [worrydream/Tangle#1]
Howdy,

I made a basic rent calculator for my friends, and they loved it. :-) I noticed while I was making it thought that I have to set every TKAdjustableNumber with data-min and data-max's to work properly. If I don't, the number appears correctly on the page after being initialised, but then dragging it immediately takes it to '10' regardless of what value it had, and thereafter it erratically changes between numbers in the range 1-10.

Is this a bug, or have I misunderstood how the class should work? If the later, sorry to waste your time! :-)

Best,
Marius

**Comment by worrydream** [comment]
data-min and data-max should be optional (and default to 1 to 10 respectively).  Could you share the code that you're using, so I can see what the issue is?  Thanks!

**Comment by ghost** [comment]
I've made a version that shows the bug at http://dl.dropbox.com/u/2986043/Projects/Rent/rent%20for%20bret.html - obviously you can view source for the code, which is straightforward (though I'm using Coffeescript rather than Javascript). I've made it so that the first two blue numbers don't have data-mins or -maxes, and the second two do; you can see that dragging the first two just sets them to 10, while the dragging the second two does what you expect.

I can see that however the code is doing exactly what you intended, so, why did you intend that? My intuitive expectation was that a TKAdjustableNumber without -min or -max would simply vary freely and continuously from its initial value.

**Comment by worrydream** [comment]
I think you're right.  I've just changed the default values, so the default min is 0, and the default max is unlimited.  That should fix the problem you're seeing.  Thanks!
