### ISSUE TITLE
Please advise on contributing options

### ISSUE THREAD

**Issue by hlfcoding** [worrydream/Tangle#17]
http://worrydream.com/ClimateChange/ is amazing. That said, I was a bit disappointed to find this repo appearing somewhat un-maintained with all pull requests open and lacking owner responses. I'd like to get confirmation this repo still has the latest code, or that pull requests should be submitted. Or if not, is it ok to just formally fork and work on my own version of this? asking because I don't see license information.

**Comment by ivant** [comment]
Some of the files (notably the JS) seem to have a comment at the top claiming that they are under MIT license.

**Comment by Rauchs** [comment]
Bret informed me via email that Tangle was under MIT license.
